-- v11 #1: Supabase runtime-data schema — the 11 tables that get real-time
-- read/write traffic during gameplay (currency, inventory, progress). Every
-- other sheet (Characters, Weapons, Equipment, Stage, StageEnemy, StageCover,
-- Enemies, PassiveConfig, GachaConfig, CurrencyExchangeConfig, TicketTopUp,
-- VipConfig, BossStage, Mission) STAYS in Google Sheets as an editable config
-- source, synced into Postgres by a separate script — not part of this file.
--
-- IDs stay TEXT (not UUID) to match the existing "player_<base36>..." /
-- "<prefix>_<...>" id format already generated by src/lib/google/player.ts
-- and friends — swapping to UUID would be a breaking format change for no
-- functional benefit.
--
-- Run this once in the Supabase SQL Editor (or `supabase db push` if you set
-- up the CLI) BEFORE any API route is switched to read/write these tables.

create table if not exists players (
  id text primary key,
  email text not null unique,
  username text not null,
  password_hash text not null default '',
  coin bigint not null default 0,
  diamond bigint not null default 0,
  ticket bigint not null default 0,
  level integer not null default 1,
  exp bigint not null default 0,
  current_stage integer not null default 1,
  current_character text not null default 'bob',
  current_weapon text not null default 'pistol',
  vip_level integer not null default 0,
  vip_exp bigint not null default 0,
  farm_stage_max_wave integer not null default 0,
  is_guest boolean not null default false,
  is_banned boolean not null default false,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  personal_milestone_tier integer not null default 0,
  personal_milestone_green_tier integer not null default 0,
  is_test_account boolean not null default false
);

create table if not exists player_weapon (
  player_id text not null references players(id) on delete cascade,
  weapon_id text not null,
  owned boolean not null default false,
  equipped boolean not null default false,
  primary key (player_id, weapon_id)
);

create table if not exists player_equipment (
  player_id text not null references players(id) on delete cascade,
  equipment_id text not null,
  slot text not null,
  equipped boolean not null default false,
  primary key (player_id, equipment_id)
);

create table if not exists player_equipment_level (
  player_id text not null references players(id) on delete cascade,
  equipment_id text not null,
  upgrade_level integer not null default 0,
  primary key (player_id, equipment_id)
);

create table if not exists player_character (
  player_id text not null references players(id) on delete cascade,
  character_id text not null,
  owned boolean not null default false,
  primary key (player_id, character_id)
);

create table if not exists player_weapon_ammo (
  player_id text not null references players(id) on delete cascade,
  weapon_id text not null,
  remaining_ammo integer not null default 0,
  last_reset_date text not null default '',
  ad_refills_today integer not null default 0,
  primary key (player_id, weapon_id)
);

create table if not exists player_passive (
  player_id text not null references players(id) on delete cascade,
  passive_id text not null,
  current_tier integer not null default 0,
  primary key (player_id, passive_id)
);

create table if not exists player_stage_progress (
  player_id text not null references players(id) on delete cascade,
  stage_id text not null,
  completed boolean not null default false,
  primary key (player_id, stage_id)
);

create table if not exists player_mission (
  player_id text not null references players(id) on delete cascade,
  mission_id text not null,
  progress integer not null default 0,
  claimed boolean not null default false,
  reset_date text not null default '',
  primary key (player_id, mission_id)
);

create table if not exists player_income (
  player_id text primary key references players(id) on delete cascade,
  green_banknote_balance integer not null default 0,
  total_withdrawn integer not null default 0
);

create table if not exists player_boss_progress (
  player_id text primary key references players(id) on delete cascade,
  boss_encounter_count integer not null default 0
);

-- Lookups every route already does (getPlayerByEmail, per-player joins).
create index if not exists idx_players_email on players (lower(email));
create index if not exists idx_player_weapon_player on player_weapon (player_id);
create index if not exists idx_player_equipment_player on player_equipment (player_id);
create index if not exists idx_player_stage_progress_player on player_stage_progress (player_id);
create index if not exists idx_player_mission_player on player_mission (player_id);
