import { getConfigRows } from "../db/configCache";

const MISSION_SHEET = "Mission";

// v16: this file used to also contain PlayerMission progress read/write
// functions backed directly by Google Sheets — those were fully superseded
// by the Supabase-backed versions in src/lib/db/mission.ts during the v12
// migration and had been dead code (zero imports) ever since. Removed as
// part of the v16 cleanup; this file now only holds the Mission CONFIG
// catalog (static list + the farm-wave milestone formula), which is still
// legitimately read from Sheets/generated in code, not per-player data.

export type MissionType = "daily" | "personal";

export interface MissionRow {
  id: string;
  type: MissionType;
  description: string;
  rewardCoin: number;
  rewardExp: number;
  rewardDiamond: number;
  targetValue: number;
  /** What kind of event this mission's progress tracks:
   *  - "kills": additive, incremented by kill count on every stage clear/exit
   *  - "stage_reached": high-water mark, set to the highest story stage number cleared
   *  - "farm_wave": high-water mark, set to the highest farm wave ever reached */
  metric: string;
}

function rowToMission(row: Record<string, string>): MissionRow {
  return {
    id: row.id,
    type: (row.type || "daily") as MissionType,
    description: row.description || "",
    rewardCoin: Number(row.rewardCoin || 0),
    rewardExp: Number(row.rewardExp || 0),
    rewardDiamond: Number(row.rewardDiamond || 0),
    targetValue: Number(row.targetValue || 1),
    metric: row.metric || "kills",
  };
}

export async function getAllMissions(): Promise<MissionRow[]> {
  const rows = await getConfigRows(MISSION_SHEET);
  return rows.map(rowToMission);
}

// v10 #2: farm-wave milestones repeat forever (wave 5, 10, 15, 20, 25, ...) —
// generated by formula instead of seeded row-by-row into the Mission sheet.
// reward = base + (milestoneIndex - 1) * step, where milestoneIndex = wave / 5.
const FARM_WAVE_INTERVAL = 5;
const FARM_WAVE_BASE = { coin: 100, exp: 100, diamond: 5 };
const FARM_WAVE_STEP = { coin: 100, exp: 100, diamond: 5 };

function farmWaveMissionId(wave: number): string {
  return `farm_wave_${wave}`;
}

/** Generates every farm-wave milestone mission from wave 5 up to (and including)
 *  the next not-yet-reached tier above `maxWaveReached`, so the Mission page
 *  always shows one upcoming milestone in addition to completed ones. */
export function generateFarmWaveMissions(maxWaveReached: number): MissionRow[] {
  const nextTier = (Math.floor(Math.max(0, maxWaveReached) / FARM_WAVE_INTERVAL) + 1) * FARM_WAVE_INTERVAL;
  const missions: MissionRow[] = [];
  for (let wave = FARM_WAVE_INTERVAL; wave <= nextTier; wave += FARM_WAVE_INTERVAL) {
    const milestoneIndex = wave / FARM_WAVE_INTERVAL;
    missions.push({
      id: farmWaveMissionId(wave),
      type: "personal",
      description: `Reach wave ${wave} in the farm stage`,
      rewardCoin: FARM_WAVE_BASE.coin + (milestoneIndex - 1) * FARM_WAVE_STEP.coin,
      rewardExp: FARM_WAVE_BASE.exp + (milestoneIndex - 1) * FARM_WAVE_STEP.exp,
      rewardDiamond: FARM_WAVE_BASE.diamond + (milestoneIndex - 1) * FARM_WAVE_STEP.diamond,
      targetValue: wave,
      metric: "farm_wave",
    });
  }
  return missions;
}
