import { getCachedSheet, invalidateSheetCache } from "./cache";
import { appendRow, findRow, findRows, updateRow, parseBool } from "./sheet";
import { addCurrency, getPlayerById } from "./player";

const MISSION_SHEET = "Mission";
const PLAYER_MISSION_SHEET = "PlayerMission";

export type MissionType = "daily" | "personal";

export interface MissionRow {
  id: string;
  type: MissionType;
  description: string;
  rewardCoin: number;
  rewardExp: number;
  rewardDiamond: number;
  targetValue: number;
  /** What kind of event this mission's progress tracks:
   *  - "kills": additive, incremented by kill count on every stage clear/exit
   *  - "stage_reached": high-water mark, set to the highest story stage number cleared
   *  - "farm_wave": high-water mark, set to the highest farm wave ever reached */
  metric: string;
}

function rowToMission(row: Record<string, string>): MissionRow {
  return {
    id: row.id,
    type: (row.type || "daily") as MissionType,
    description: row.description || "",
    rewardCoin: Number(row.rewardCoin || 0),
    rewardExp: Number(row.rewardExp || 0),
    rewardDiamond: Number(row.rewardDiamond || 0),
    targetValue: Number(row.targetValue || 1),
    metric: row.metric || "kills",
  };
}

export async function getAllMissions(): Promise<MissionRow[]> {
  const { rows } = await getCachedSheet(MISSION_SHEET);
  return rows.map(rowToMission);
}

// v10 #2: farm-wave milestones repeat forever (wave 5, 10, 15, 20, 25, ...) —
// generated by formula instead of seeded row-by-row into the Mission sheet.
// reward = base + (milestoneIndex - 1) * step, where milestoneIndex = wave / 5.
const FARM_WAVE_INTERVAL = 5;
const FARM_WAVE_BASE = { coin: 100, exp: 100, diamond: 5 };
const FARM_WAVE_STEP = { coin: 100, exp: 100, diamond: 5 };

function farmWaveMissionId(wave: number): string {
  return `farm_wave_${wave}`;
}

/** Generates every farm-wave milestone mission from wave 5 up to (and including)
 *  the next not-yet-reached tier above `maxWaveReached`, so the Mission page
 *  always shows one upcoming milestone in addition to completed ones. */
export function generateFarmWaveMissions(maxWaveReached: number): MissionRow[] {
  const nextTier = (Math.floor(Math.max(0, maxWaveReached) / FARM_WAVE_INTERVAL) + 1) * FARM_WAVE_INTERVAL;
  const missions: MissionRow[] = [];
  for (let wave = FARM_WAVE_INTERVAL; wave <= nextTier; wave += FARM_WAVE_INTERVAL) {
    const milestoneIndex = wave / FARM_WAVE_INTERVAL;
    missions.push({
      id: farmWaveMissionId(wave),
      type: "personal",
      description: `Reach wave ${wave} in the farm stage`,
      rewardCoin: FARM_WAVE_BASE.coin + (milestoneIndex - 1) * FARM_WAVE_STEP.coin,
      rewardExp: FARM_WAVE_BASE.exp + (milestoneIndex - 1) * FARM_WAVE_STEP.exp,
      rewardDiamond: FARM_WAVE_BASE.diamond + (milestoneIndex - 1) * FARM_WAVE_STEP.diamond,
      targetValue: wave,
      metric: "farm_wave",
    });
  }
  return missions;
}

/** Static sheet missions + this player's currently-visible farm-wave milestones, merged. */
export async function getAllMissionsForPlayer(playerId: string, farmWaveHint?: number): Promise<MissionRow[]> {
  const staticMissions = await getAllMissions();
  let maxWave = farmWaveHint ?? 0;
  if (farmWaveHint === undefined) {
    const player = await getPlayerById(playerId);
    maxWave = player?.farmStageMaxWave ?? 0;
  }
  return [...staticMissions, ...generateFarmWaveMissions(maxWave)];
}

export interface PlayerMissionRow {
  playerId: string;
  missionId: string;
  progress: number;
  claimed: boolean;
  /** Only meaningful for "daily" missions — the YYYY-MM-DD (UTC) this row's progress was last reset. */
  resetDate: string;
}

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function rowToPlayerMission(r: Record<string, string>): PlayerMissionRow {
  return {
    playerId: r.playerId,
    missionId: r.missionId,
    progress: Number(r.progress || 0),
    claimed: parseBool(r.claimed),
    resetDate: r.resetDate || "",
  };
}

export async function getPlayerMissionProgress(playerId: string): Promise<PlayerMissionRow[]> {
  const missions = await getAllMissionsForPlayer(playerId);
  const rows = await findRows(PLAYER_MISSION_SHEET, (r) => r.playerId === playerId);
  const today = todayUtc();

  return rows.map((r) => {
    const parsed = rowToPlayerMission(r);
    const mission = missions.find((m) => m.id === parsed.missionId);
    // Daily missions that were last reset on an earlier date display as fresh
    // (progress 0, unclaimed) even though the sheet row hasn't been rewritten
    // yet — the actual reset write happens lazily on the next progress/claim call.
    if (mission?.type === "daily" && parsed.resetDate !== today) {
      return { ...parsed, progress: 0, claimed: false };
    }
    return parsed;
  });
}

/** Ensures a player's progress row for `mission` reflects "today" if it's a daily mission, resetting it in the sheet if stale. Returns the up-to-date row. */
async function getOrCreateProgressRow(playerId: string, mission: MissionRow) {
  const found = await findRow(PLAYER_MISSION_SHEET, (r) => r.playerId === playerId && r.missionId === mission.id);

  if (!found) {
    await appendRow(PLAYER_MISSION_SHEET, { playerId, missionId: mission.id, progress: 0, claimed: false, resetDate: todayUtc() });
    invalidateSheetCache(PLAYER_MISSION_SHEET);
    return findRow(PLAYER_MISSION_SHEET, (r) => r.playerId === playerId && r.missionId === mission.id);
  }

  if (mission.type === "daily" && found.row.resetDate !== todayUtc()) {
    await updateRow(PLAYER_MISSION_SHEET, found.rowIndex, { progress: 0, claimed: false, resetDate: todayUtc() });
    invalidateSheetCache(PLAYER_MISSION_SHEET);
    return findRow(PLAYER_MISSION_SHEET, (r) => r.playerId === playerId && r.missionId === mission.id);
  }

  return found;
}

/** Bumps progress on every mission matching a given metric (e.g. "kills"). Called from game/complete. Additive — use for counters that only ever go up by the event's amount (never a "reached X" high-water value). */
export async function incrementMissionProgress(playerId: string, metric: string, amount: number, allMissions?: MissionRow[]): Promise<void> {
  if (amount <= 0) return;
  const missions = allMissions ?? await getAllMissionsForPlayer(playerId);
  const matching = missions.filter((m) => m.metric === metric);

  for (const mission of matching) {
    const found = await getOrCreateProgressRow(playerId, mission);
    if (!found || parseBool(found.row.claimed)) continue;
    const newProgress = Math.min(mission.targetValue, Number(found.row.progress || 0) + amount);
    await updateRow(PLAYER_MISSION_SHEET, found.rowIndex, { progress: newProgress });
  }
  invalidateSheetCache(PLAYER_MISSION_SHEET);
}

/** Sets progress to max(current, value) (capped at each mission's targetValue) for
 *  every mission matching `metric` — for "reached wave/stage X" style milestones,
 *  where `value` is the new personal-best, not a delta to add. */
export async function setMissionProgressIfHigher(playerId: string, metric: string, value: number, allMissions?: MissionRow[]): Promise<void> {
  if (value <= 0) return;
  const missions = allMissions ?? await getAllMissionsForPlayer(playerId, value);
  const matching = missions.filter((m) => m.metric === metric);

  for (const mission of matching) {
    const found = await getOrCreateProgressRow(playerId, mission);
    if (!found || parseBool(found.row.claimed)) continue;
    const current = Number(found.row.progress || 0);
    const next = Math.min(mission.targetValue, Math.max(current, value));
    if (next !== current) await updateRow(PLAYER_MISSION_SHEET, found.rowIndex, { progress: next });
  }
  invalidateSheetCache(PLAYER_MISSION_SHEET);
}

export async function claimMission(playerId: string, missionId: string): Promise<{ rewardCoin: number; rewardExp: number; rewardDiamond: number }> {
  const missions = await getAllMissionsForPlayer(playerId);
  const mission = missions.find((m) => m.id === missionId);
  if (!mission) throw new Error("Mission not found");

  const found = await getOrCreateProgressRow(playerId, mission);
  const progress = found ? Number(found.row.progress || 0) : 0;
  const claimed = found ? parseBool(found.row.claimed) : false;

  if (claimed) throw new Error("Already claimed");
  if (progress < mission.targetValue) throw new Error("Mission not complete yet");

  await addCurrency(playerId, { coin: mission.rewardCoin, exp: mission.rewardExp, diamond: mission.rewardDiamond });

  if (found) {
    await updateRow(PLAYER_MISSION_SHEET, found.rowIndex, { claimed: true });
  } else {
    await appendRow(PLAYER_MISSION_SHEET, { playerId, missionId, progress: mission.targetValue, claimed: true, resetDate: todayUtc() });
  }
  invalidateSheetCache(PLAYER_MISSION_SHEET);

  return { rewardCoin: mission.rewardCoin, rewardExp: mission.rewardExp, rewardDiamond: mission.rewardDiamond };
}
